on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: jdkaim-minesweeper    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: .\Minesweeper.Web\obj\Release\Package\PackageTmp

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore Minesweeper.sln
 
    - name: Build Web App
      run: msbuild Minesweeper.sln /p:Configuration=Release /p:DeployOnBuild=true
    
    - name: Run Unit Tests
      run: vstest.console.exe **\*.Tests.dll
      
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Log out of Azure
      run: |
        az logout
